name: 'Usage of download-artifact GitHub Action'
on:
push:
    branches:
        - main
jobs:
deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
